apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"mongod","namespace":"mutants"},"spec":{"replicas":3,"selector":{"matchLabels":{"role":"mongo"}},"serviceName":"mongodb-service","template":{"metadata":{"labels":{"environment":"test","replicaset":"MainRepSet","role":"mongo"}},"spec":{"containers":[{"command":["mongod","--bind_ip","0.0.0.0","--replSet","MainRepSet"],"image":"mongo","name":"mongod-container","ports":[{"containerPort":27017}],"resources":{"requests":{"cpu":0.2,"memory":"200Mi"}},"volumeMounts":[{"mountPath":"/data/db","name":"mongodb-persistent-storage-claim"}]}],"terminationGracePeriodSeconds":10}},"volumeClaimTemplates":[{"metadata":{"annotations":{"volume.beta.kubernetes.io/storage-class":"standard"},"name":"mongodb-persistent-storage-claim"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"1Gi"}}}}]}}
  creationTimestamp: "2020-12-28T23:08:25Z"
  generation: 1
  name: mongod
  namespace: mutants
  resourceVersion: "705789"
  selfLink: /apis/apps/v1/namespaces/mutants/statefulsets/mongod
  uid: 574d5a60-eefe-4d27-90f0-fa570f6a8954
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      role: mongo
  serviceName: mongodb-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        environment: test
        replicaset: MainRepSet
        role: mongo
    spec:
      containers:
        - command:
            - mongod
            - --bind_ip
            - 0.0.0.0
            - --replSet
            - MainRepSet
          image: mongo
          imagePullPolicy: Always
          name: mongod-container
          ports:
            - containerPort: 27017
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-persistent-storage-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        annotations:
          volume.beta.kubernetes.io/storage-class: standard
        creationTimestamp: null
        name: mongodb-persistent-storage-claim
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
      status:
        phase: Pending
status:
  collisionCount: 0
  currentReplicas: 3
  currentRevision: mongod-845b4bf66
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updateRevision: mongod-845b4bf66
  updatedReplicas: 3
