apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"name":"mongo"},"name":"mongodb-service","namespace":"mutants"},"spec":{"clusterIP":"None","ports":[{"port":27017,"targetPort":27017}],"selector":{"role":"mongo"}}}
  creationTimestamp: "2020-12-28T23:09:05Z"
  labels:
    name: mongo
  name: mongodb-service
  namespace: mutants
  resourceVersion: "705675"
  selfLink: /api/v1/namespaces/mutants/services/mongodb-service
  uid: dd1757b2-4d40-43fb-ac5d-6e5ad10911af
spec:
  clusterIP: None
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    role: mongo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}