apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-12-28T02:41:14Z"
  generation: 1
  labels:
    app: mutants-api
  name: mutants-api
  namespace: mutants
  resourceVersion: "389700"
  selfLink: /apis/apps/v1/namespaces/mutants/deployments/mutants-api
  uid: 3950e4d2-a16f-4b51-ba33-d18f57086d12
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mutants-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mutants-api
    spec:
      containers:
        - image: gcr.io/mutants-299814/github.com/sebalvarez97/mutants:afcca32
          imagePullPolicy: IfNotPresent
          name: mutants-1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: "2020-12-28T02:41:42Z"
      lastUpdateTime: "2020-12-28T02:41:42Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-12-28T02:41:14Z"
      lastUpdateTime: "2020-12-28T02:41:42Z"
      message: ReplicaSet "mutants-api-858c6fcd66" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
