apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    gcb-build-id: ffb9e4f5-80a3-4eec-b1b2-d4425f10142e
    gcb-trigger-id: 0692f685-b890-47d4-a0f5-d4a299c75502
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"8","gcb-build-id":"ffb9e4f5-80a3-4eec-b1b2-d4425f10142e","gcb-trigger-id":"0692f685-b890-47d4-a0f5-d4a299c75502"},"creationTimestamp":"2020-12-28T02:41:14Z","generation":8,"labels":{"app":"mutants-api","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"mutants-api","app.kubernetes.io/version":"1154fa7fef56944c82ca43c5ba6bb34476ef1878"},"name":"mutants-api","namespace":"mutants","resourceVersion":"720359","selfLink":"/apis/apps/v1/namespaces/mutants/deployments/mutants-api","uid":"3950e4d2-a16f-4b51-ba33-d18f57086d12"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"mutants-api"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"gcb-build-id":"ffb9e4f5-80a3-4eec-b1b2-d4425f10142e","gcb-trigger-id":"0692f685-b890-47d4-a0f5-d4a299c75502"},"creationTimestamp":null,"labels":{"app":"mutants-api","app.kubernetes.io/managed-by":"gcp-cloud-build-deploy","app.kubernetes.io/name":"mutants-api","app.kubernetes.io/version":"1154fa7fef56944c82ca43c5ba6bb34476ef1878"}},"spec":{"containers":[{"env":[{"name":"MONGO_URI","value":"mongodb://mongod-0.mongodb-service.mutants.svc.cluster.local,mongod-1.mongodb-service.mutants.svc.cluster.local,mongod-2.mongodb-service.mutants.svc.cluster.local:27017"}],"image":"gcr.io/mutants-299814/github.com/sebalvarez97/mutants@sha256:9e122e92dcebaac88e975df7c06f5d1a8ae02da84916c3a6d4c214edf75af96d","imagePullPolicy":"IfNotPresent","name":"mutants-1","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2020-12-28T02:41:42Z","lastUpdateTime":"2020-12-28T02:41:42Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2020-12-28T02:41:14Z","lastUpdateTime":"2020-12-29T00:04:55Z","message":"ReplicaSet \"mutants-api-56db4dd7bf\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":8,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2020-12-28T02:41:14Z"
  generation: 9
  labels:
    app: mutants-api
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: mutants-api
    app.kubernetes.io/version: 1154fa7fef56944c82ca43c5ba6bb34476ef1878
  name: mutants-api
  namespace: mutants
  resourceVersion: "1066921"
  selfLink: /apis/apps/v1/namespaces/mutants/deployments/mutants-api
  uid: 3950e4d2-a16f-4b51-ba33-d18f57086d12
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mutants-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        gcb-build-id: ffb9e4f5-80a3-4eec-b1b2-d4425f10142e
        gcb-trigger-id: 0692f685-b890-47d4-a0f5-d4a299c75502
      creationTimestamp: null
      labels:
        app: mutants-api
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: mutants-api
        app.kubernetes.io/version: 1154fa7fef56944c82ca43c5ba6bb34476ef1878
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://mongod-0.mongodb-service.mutants.svc.cluster.local,mongod-1.mongodb-service.mutants.svc.cluster.local,mongod-2.mongodb-service.mutants.svc.cluster.local:27017
          image: gcr.io/mutants-299814/github.com/sebalvarez97/mutants@sha256:9e122e92dcebaac88e975df7c06f5d1a8ae02da84916c3a6d4c214edf75af96d
          imagePullPolicy: IfNotPresent
          name: mutants-1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
    - lastTransitionTime: "2020-12-28T02:41:42Z"
      lastUpdateTime: "2020-12-28T02:41:42Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-12-28T02:41:14Z"
      lastUpdateTime: "2020-12-29T22:32:10Z"
      message: ReplicaSet "mutants-api-774595dfcc" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 9
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3